pipeline{
    agent any
    stages{
        stage('Build'){
            steps{
                sh 'echo "am building image with Docker"'
            }
        }
        stage('Test'){
            steps{
                sh 'echo "am testing the image of Docker"'
            }
        }
        stage('Deploy'){
            steps{
                sh 'echo "am deploying the image of K8"'
            }
        }
        stage('Menory'){
            stages{
                sh '''
                    lscpu
                '''
            }
        }
    }
}