pipeline{
    agent any
    stages{
        stage('Build'){
            steps{
                sh 'echo "The build phase"'
            }
        }
        stage('Test'){
            steps{
                sh 'echo "The test phase..."'
            }
        }
        stage('info'){
            steps{
                sh 'lscpu'
            }
        }
    }
}